routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::group(['middleware' => 'auth'], function(){
	Route::get('/', 'HomeController@task_center');
	//Route::get('/home', 'HomeController@task_center');
	//Route::get('/dashboard', 'HomeController@task_center');


Route::get('mission_and_vision', 'HomeController@mission_and_vision');
Route::get('goals_and_objective', 'HomeController@goals_and_objective');
Route::get('task_center/{date}', 'HomeController@task_center');
Route::get('deliverables_and_deadlines', 'HomeController@deliverables_and_deadlines');
Route::get('performance_and_evaluations', 'HomeController@performance_and_evaluations');
Route::get('community_and_social_responsibility', 'HomeController@community_and_social_responsibility');

// Employee routes
Route::resource('employee', 'ErpEmployeeController');
Route::get('create_operation_modal', 'ErpEmployeeController@create_operation_modal');
Route::get('edit_operation_modal/{id}', 'ErpEmployeeController@edit_operation_modal');
Route::get('create_md_employee_modal', 'ErpEmployeeController@create_md_employee_modal');
Route::get('edit_md_employee_modal/{id}', 'ErpEmployeeController@edit_md_employee_modal');
Route::get('deleteEmployeeView/{id}', 'ErpEmployeeController@deleteEmployeeView');
Route::get('deleteEmployee/{id}', 'ErpEmployeeController@deleteEmployee');
Route::get('view_employee/{id}', 'ErpEmployeeController@viewEmployee');
Route::get('viewEmployeeById/{id}', 'ErpEmployeeController@viewEmployeeById');
Route::get('showAdjustEmployeeView/{device_USERID}', 'ErpEmployeeController@showAdjustEmployeeView');
Route::put('employee_time_adjust/{device_USERID}', 'ErpEmployeeController@employee_time_adjust');


//employee attendence
Route::resource('employee-attendence', 'ErpEmployeeAttendenceController');
Route::get('view-emplyoee-atten-details/{id}', 'ErpEmployeeAttendenceController@viewAttenDetails');
Route::post('attendence', 'ErpEmployeeAttendenceController@save_attendence');
Route::get('get-api-last-call-time', 'ErpEmployeeAttendenceController@getApiLastCallTime');
Route::post('emp_late_time', 'ErpEmployeeAttendenceController@emp_late_time');
//Route::get('emp_late_time', 'ErpEmployeeAttendenceController@emp_late_time');


// Base group routes
Route::resource('base_group', 'ErpBaseGroupController');
Route::get('deleteBaseGroupView/{id}', 'ErpBaseGroupController@deleteBaseGroupView');
Route::get('deleteBaseGroup/{id}', 'ErpBaseGroupController@deleteBaseGroup');

// Base setup routes
Route::resource('base_setup', 'ErpBaseSetupController');
Route::get('deleteBaseSetupView/{id}', 'ErpBaseSetupController@deleteBaseSetupView');
Route::get('deleteBaseSetup/{id}', 'ErpBaseSetupController@deleteBaseSetup');

// Designation routes
Route::resource('designation', 'ErpDesignationController');
Route::get('deleteDesignationView/{id}', 'ErpDesignationController@deleteDesignationView');
Route::get('deleteDesignation/{id}', 'ErpDesignationController@deleteDesignation');

// Sector routes
Route::resource('sector','SectorController');
Route::get('create_sector_modal', 'SectorController@create_sector_modal');
Route::get('edit_sector_modal/{id}', 'SectorController@edit_sector_modal');
Route::get('deleteSectorView/{id}', 'SectorController@deleteSectorView');
Route::get('deleteSector/{id}', 'SectorController@destroy');

// Company routes
Route::resource('company','CompanyController');
Route::get('create_company_modal', 'CompanyController@create_company_modal');
Route::get('edit_company_modal/{id}', 'CompanyController@edit_company_modal');
Route::get('deleteCompanyView/{id}', 'CompanyController@deleteSectorView');
Route::get('deleteCompany/{id}', 'CompanyController@destroy');

// Focus routes
Route::resource('focus','MdFocusController');
Route::get('edit_focus_modal/{id}', 'MdFocusController@edit_focus_modal');
Route::get('create_focus_modal', 'MdFocusController@create_focus_modal');
Route::get('deleteFocusView/{id}', 'MdFocusController@deleteFocusView');
Route::get('deleteFocus/{id}', 'MdFocusController@deleteFocus');

// Assign projects routes
Route::resource('assign_project','MdAssignProjectController');
Route::get('deleteAssignProjectView/{id}', 'MdAssignProjectController@deleteAssignProjectView');
Route::get('deleteAssignProject/{id}', 'MdAssignProjectController@deleteAssignProject');

// Project
Route::resource('project', 'ErpProjectController');
Route::get('create_project_modal', 'ErpProjectController@create_project_modal');
Route::get('edit_project_modal/{id}', 'ErpProjectController@edit_project_modal');
Route::get('deleteProjectView/{id}', 'ErpProjectController@deleteProjectView');
Route::get('deleteProject/{id}', 'ErpProjectController@deleteProject');

// Department routes
Route::resource('department', 'ErpDepartmentController');
Route::get('create_department_modal', 'ErpDepartmentController@create_department_modal');
Route::get('edit_department_modal/{id}', 'ErpDepartmentController@edit_department_modal');
Route::get('deleteDepartmentView/{id}', 'ErpDepartmentController@deleteDepartmentView');
Route::get('deleteDepartment/{id}', 'ErpDepartmentController@deleteDepartment');

// Assign task
Route::resource('emp_task_assign', 'MdAssignTaskController');
Route::get('assign_task/{id}', 'MdAssignTaskController@add_employee_task');
Route::get('view_assign_task/{id}', 'MdAssignTaskController@show_employee_task');

//For Generating report
Route::get('generate_report', 'HomeController@generate_report');
Route::post('search_fields', 'HomeController@generate_search_report');
// Route::get('calculate_hours', 'HomeController@calculate_hours');

Route::get('show_res_by_date/{date}', 'HomeController@show_res_by_date');

// Role route
Route::resource('role', 'ErpRoleController');
Route::get('deleteRoleView/{id}', 'ErpRoleController@deleteRoleView');
Route::get('deleteRole/{id}', 'ErpRoleController@deleteRole');


// User route
Route::resource('user', 'ErpUserController');
Route::get('deleteUserView/{id}', 'ErpUserController@deleteUserView');
Route::get('deleteUser/{id}', 'ErpUserController@deleteUser');

Route::get('fill_out_time_data', 'ErpEmployeeAttendenceController@fill_out_time_data');

Route::get('search_employee_attendance','ErpEmployeeAttendenceController@searchAttendance');

Route::get('/selected_attendance', 'ErpEmployeeAttendenceController@selected_attendance');
Route::get('/get_selected_attendance', 'ErpEmployeeAttendenceController@get_selected_attendance');

});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'employee_id', 'first_name', 'last_name', 'name', 'email', 'role_id', 'password', 'active_status'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

resources/views/backEnd/users/create.blade.php
@extends('backEnd.master')
@section('mainContent')

<div class="container-fluid container_margin">
	<div class="row">
		<div class="col-md-4">
		
			@if(session()->has('message-success'))
			<div class="alert alert-success mb-3 background-success" role="alert">
				{{ session()->get('message-success') }}
				<button type="button" class="close" data-dismiss="alert" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			@elseif(session()->has('message-danger'))
			<div class="alert alert-danger">
				{{ session()->get('message-danger') }}
				<button type="button" class="close" data-dismiss="alert" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			@endif
			@if(session()->has('message-success-delete'))
				<div class="alert alert-danger mb-3 background-danger" role="alert">
					{{ session()->get('message-success-delete') }}
					<button type="button" class="close" data-dismiss="alert" aria-label="Close">
						<span aria-hidden="true">&times;</span>
					</button>
				</div>
			@elseif(session()->has('message-danger-delete'))
				<div class="alert alert-danger">
					{{ session()->get('message-danger-delete') }}
					<button type="button" class="close" data-dismiss="alert" aria-label="Close">
						<span aria-hidden="true">&times;</span>
					</button>
				</div>
			@endif

			<div class="card">
				<div class="card-header">
					<h5>Add New User</h5>
				</div>
				<div class="card-block">
					{{ Form::open(['class' => '', 'files' => true, 'url' => 'user',
					'method' => 'POST', 'enctype' => 'multipart/form-data']) }}
						<div class="row">
							<div class="col-md-12">

								<div class="form-group row">
					                <label for="employee_id" class="col-md-4 col-form-label text-md-right">{{ __('Employee ID') }}</label>
					                <div class="col-md-6">
						                <select class="form-control {{ $errors->has('employee_id') ? ' is-invalid' : '' }}" name="employee_id" id="employee_id">
										<option value="">Select Employee Name</option>
										@if(isset($employees))
											@foreach($employees as $employee)
												<option value='{"id": "{{ $employee->id }}","first_name": "{{$employee->first_name}}","last_name":"{{$employee->last_name}}","full_name":"{{$employee->full_name}}","email":"{{$employee->email}}" }' {{ old('employee_id')== $employee->id ? 'selected' : ''  }} >{{$employee->full_name}}</option>
											@endforeach
										@endif
										</select>
										@if ($errors->has('employee_id'))
										<span class="invalid-feedback invalid-select" role="alert">
											<strong>{{ $errors->first('employee_id') }}</strong>
										</span>
										@endif
									</div>
					            </div>

								<div class="form-group row">
					                <label for="first_name" class="col-md-4 col-form-label text-md-right">{{ __('First Name') }}</label>

					                <div class="col-md-6">
					                    <input id="first_name" type="text" class="form-control{{ $errors->has('first_name') ? ' is-invalid' : '' }}" name="first_name" value="{{ old('first_name') }}" autocomplete="off" >

					                    @if ($errors->has('first_name'))
					                        <span class="invalid-feedback" role="alert">
					                            <strong>{{ $errors->first('first_name') }}</strong>
					                        </span>
					                    @endif
					                </div>
					            </div>
					            <div class="form-group row">
					                <label for="last_name" class="col-md-4 col-form-label text-md-right">{{ __('Last Name') }}</label>

					                <div class="col-md-6">
					                    <input id="last_name" type="text" class="form-control{{ $errors->has('last_name') ? ' is-invalid' : '' }}" name="last_name" value="{{ old('last_name') }}" autocomplete="off" >

					                    @if ($errors->has('last_name'))
					                        <span class="invalid-feedback" role="alert">
					                            <strong>{{ $errors->first('last_name') }}</strong>
					                        </span>
					                    @endif
					                </div>
					            </div>

					            <div class="form-group row">
					                <label for="email" class="col-md-4 col-form-label text-md-right">{{ __('E-Mail Address') }}</label>

					                <div class="col-md-6">
					                    <input id="email" type="email" class="form-control{{ $errors->has('email') ? ' is-invalid' : '' }}" name="email" value="{{ old('email') }}" autocomplete="off">

					                    @if ($errors->has('email'))
					                        <span class="invalid-feedback" role="alert">
					                            <strong>{{ $errors->first('email') }}</strong>
					                        </span>
					                    @endif
					                </div>
					            </div>

					            <div class="form-group row">
					                <label for="role_id" class="col-md-4 col-form-label text-md-right">{{ __('Role ID') }}</label>
					                <div class="col-md-6">
						                <select class="form-control {{ $errors->has('role_id') ? ' is-invalid' : '' }}" name="role_id" id="role_id">
										<option value="">Select Role ID</option>
										@if(isset($roles))
											@foreach($roles as $role)
												<option value="{{ $role->id }}" {{ old('role_id')== $role->id ? 'selected' : ''  }} >{{$role->role_name}}</option>
											@endforeach
										@endif
										</select>
										@if ($errors->has('role_id'))
										<span class="invalid-feedback invalid-select" role="alert">
											<strong>{{ $errors->first('role_id') }}</strong>
										</span>
										@endif
									</div>
					            </div>

					            <div class="form-group row">
					                <label for="password" class="col-md-4 col-form-label text-md-right">{{ __('Password') }}</label>

					                <div class="col-md-6">
					                    <input id="password" type="password" class="form-control{{ $errors->has('password') ? ' is-invalid' : '' }}" name="password">

					                    @if ($errors->has('password'))
					                        <span class="invalid-feedback" role="alert">
					                            <strong>{{ $errors->first('password') }}</strong>
					                        </span>
					                    @endif
					                </div>
					            </div>

					            <div class="form-group row">
					                <label for="password_confirmation" class="col-md-4 col-form-label text-md-right">{{ __('Confirm Password') }}</label>

					                <div class="col-md-6">
					                    <input id="password_confirmation" type="password" class="form-control {{ $errors->has('password_confirmation') ? ' is-invalid' : '' }}" name="password_confirmation" >
					                    @if ($errors->has('password_confirmation'))
					                        <span class="invalid-feedback" role="alert">
					                            <strong>{{ $errors->first('password_confirmation') }}</strong>
					                        </span>
					                    @endif
					                </div>
					            </div>
							</div>
						</div>
						<div class="form-group row mt-4">
							<div class="col-sm-12 text-center">
								<button type="submit" class="btn btn-primary m-b-0">Add user</button>
							</div>
						</div>
					{{ Form::close()}}
				</div>
			</div>
		</div>
		<div class="col-md-8">
			<div class="card">
				<div class="card-header">
					<h5>Users</h5>
				</div>
				<div class="card-block">
					<div class="dt-responsive table-responsive">
					<table id="basic-btn" class="table table-striped table-bordered nowrap basic-btn">
						<thead>
							<tr>
								<th>User id</th>
								<th>User Name</th>
								<th>Email</th>
								<th>Actions</th>
							</tr>
						</thead>
						<tbody>
							@if(isset($users))
								@php $i = 1 @endphp
								@foreach($users as $user)
								<tr>
									<td>{{$i++}}</td>
									<td>{{$user->name}}</td>
									<td>{{$user->email}}</td>
									<td>
										{{-- <a href="" title="view"><button type="button" class="btn btn-success action-icon"><i class="fa fa-eye"></i></button></a> --}}

										<a href="{{ route('user.edit',$user->id) }}" class="edit_icon" title="edit"><i class="fa fa-edit"></i></a>
										<a class="modalLink delete_icon" title="Delete User" data-modal-size="modal-md" href="{{url('deleteUserView', $user->id)}}">
											<i class="fa fa-trash"></i>
										</a>
								    </td>
								</tr>
								@endforeach
							@endif
						</tbody>
					</table>
				</div>
				</div>
			</div>
		</div>
	</div>

</div>

@endSection

resources/views/backEnd/users/edit.blade.php
@extends('backEnd.master')
@section('mainContent')
<div class="row">
	<div class="col-md-4">
		
		@if(session()->has('message-danger'))
		<div class="alert alert-danger">
			{{ session()->get('message-danger') }}
			<button type="button" class="close" data-dismiss="alert" aria-label="Close">
				<span aria-hidden="true">&times;</span>
			</button>
		</div>
		@endif

		<div class="card">
			<div class="card-header">
				<h5>Edit User</h5>
			</div>
			<div class="card-block">
				{{ Form::open(['class' => 'form-horizontal', 'files' => true, 'url' => 'user/'.$editData->id, 'method' => 'PUT', 'enctype' => 'multipart/form-data']) }}
					<div class="row">
						<div class="col-md-12">
							<div class="form-group row">
				                <label for="first_name" class="col-md-4 col-form-label text-md-right">{{ __('First Name') }}</label>

				                <div class="col-md-6">
				                    <input id="first_name" type="text" class="form-control{{ $errors->has('first_name') ? ' is-invalid' : '' }}" name="first_name" value="{{ $editData->first_name }}" autocomplete="off">

				                    @if ($errors->has('first_name'))
				                        <span class="invalid-feedback" role="alert">
				                            <strong>{{ $errors->first('first_name') }}</strong>
				                        </span>
				                    @endif
				                </div>
				            </div>
				            <div class="form-group row">
				                <label for="last_name" class="col-md-4 col-form-label text-md-right">{{ __('Last Name') }}</label>

				                <div class="col-md-6">
				                    <input id="last_name" type="text" class="form-control{{ $errors->has('last_name') ? ' is-invalid' : '' }}" name="last_name" value="{{ $editData->last_name }}" autocomplete="off">

				                    @if ($errors->has('last_name'))
				                        <span class="invalid-feedback" role="alert">
				                            <strong>{{ $errors->first('last_name') }}</strong>
				                        </span>
				                    @endif
				                </div>
				            </div>

				            <div class="form-group row">
				                <label for="email" class="col-md-4 col-form-label text-md-right">{{ __('E-Mail Address') }}</label>

				                <div class="col-md-6">
				                    <input id="email" type="email" class="form-control{{ $errors->has('email') ? ' is-invalid' : '' }}" name="email" value="{{ $editData->email }}" autocomplete="off">

				                    @if ($errors->has('email'))
				                        <span class="invalid-feedback" role="alert">
				                            <strong>{{ $errors->first('email') }}</strong>
				                        </span>
				                    @endif
				                </div>
				            </div>

				            <div class="form-group row">
				                <label for="role_id" class="col-md-4 col-form-label text-md-right">{{ __('Role ID') }}</label>
				                <div class="col-md-6">
					                <select name="role_id" id="role_id" class="js-example-basic-single col-sm-12">
									    <option value="">Select role</option>
									    @if(isset($roles))
										@foreach($roles as $key=>$value)
										<option value="{{$value->id}}"
											@if(isset($editData))
												@if($editData->role_id == $value->id)
													selected
												@endif
											@endif
											>{{$value->role_name}}</option>
											@endforeach
											@endif
									</select>

									@if ($errors->has('role_id'))
									<span class="invalid-feedback invalid-select" role="alert">
										<span class="messages"><strong>{{ $errors->first('role_id') }}</strong></span>
									</span>
									@endif
								</div>
				            </div>

				            <div class="form-group row">
				                <label for="previous_password" class="col-md-4 col-form-label text-md-right">{{ __('Previous Password') }}</label>

				                <div class="col-md-6">
				                    <input id="previous_password" type="password" class="form-control{{ $errors->has('previous_password') ? ' is-invalid' : '' }}" name="previous_password">

				                    @if ($errors->has('previous_password'))
				                        <span class="invalid-feedback" role="alert">
				                            <strong>{{ $errors->first('previous_password') }}</strong>
				                        </span>
				                    @endif
				                </div>
				            </div>

				            <div class="form-group row">
				                <label for="password" class="col-md-4 col-form-label text-md-right">{{ __('New Password') }}</label>

				                <div class="col-md-6">
				                    <input id="password" type="password" class="form-control{{ $errors->has('password') ? ' is-invalid' : '' }}" name="password">

				                    @if ($errors->has('password'))
				                        <span class="invalid-feedback" role="alert">
				                            <strong>{{ $errors->first('password') }}</strong>
				                        </span>
				                    @endif
				                </div>
				            </div>


				            <div class="form-group row">
				                <label for="password-confirm" class="col-md-4 col-form-label text-md-right">{{ __('Confirm Password') }}</label>

				                <div class="col-md-6">
				                    <input id="password-confirm" type="password" class="form-control" name="password_confirmation">
				                </div>
				            </div>
						</div>
					</div>
					<div class="form-group row mt-4">
						<div class="col-sm-12 text-center">
							<button type="submit" class="btn btn-primary m-b-0">Update</button>
						</div>
					</div>
				{{ Form::close()}}
			</div>
		</div>
	</div>

</div>

@endSection